name: plasclass
description: Classifies sequences in a FASTA file as plasmid or chromosomal
keywords:
  - plasmid
  - classification
  - metagenomics
tools:
  - plasclass:
      description: Classify plasmid sequences in metagenomic assemblies
      homepage: https://github.com/Shamir-Lab/PlasClass
      documentation: https://github.com/Shamir-Lab/PlasClass
      licence: ["MIT"]
input:
  - meta:
      type: map
      description: Groovy Map containing sample information e.g. [id:'sample1']
  - fasta:
      type: file
      description: Input FASTA file of assembled contigs
      pattern: "*.{fasta,fa,fasta.gz,fa.gz}"
output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - report:
      type: file
      description: PlasClass classification scores for each contig
      pattern: "*.plasclass.txt"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@leilanasirzadeh"
